// Initial seed data for Social Media Lead Extractor demo

export const INITIAL_SOCIAL_ACCOUNTS = [
  {
    id: "SA-linkedin",
    platform: "LinkedIn",
    name: "LinkedIn Page & Lead Forms",
    handle: "@saivyy-technologies",
    accountType: "Company Page & Sponsored Ads",
    status: 1,
    followers: "64.2K Followers",
    lastSync: "Just now",
    icon: "linkedin",
    color: "#0A66C2",
    metrics: JSON.stringify({ inquiries: 67, extracted: 28, yield: "41.8%" }),
    trackedKeywords: JSON.stringify(["B2B CRM", "Sales Automation", "Enterprise Demo", "#LeadGen"]),
    userId: "U-117bb402-3724-4580-9da9-01311b759889"
  },
  {
    id: "SA-meta",
    platform: "Meta",
    name: "Meta Business (Facebook & Ads)",
    handle: "@saivyy.crm.official",
    accountType: "Page & Instant Lead Forms",
    status: 1,
    followers: "48.5K Followers",
    lastSync: "3 mins ago",
    icon: "meta",
    color: "#1877F2",
    metrics: JSON.stringify({ inquiries: 42, extracted: 14, yield: "33.3%" }),
    trackedKeywords: JSON.stringify(["#crm", "#b2bsales", "enterprise demo", "software"]),
    userId: "U-117bb402-3724-4580-9da9-01311b759889"
  },
  {
    id: "SA-instagram",
    platform: "Instagram",
    name: "Instagram Professional Suite",
    handle: "@saivyy_technologies",
    accountType: "Business Account & Reels",
    status: 1,
    followers: "29.8K Followers",
    lastSync: "1 min ago",
    icon: "instagram",
    color: "#E4405F",
    metrics: JSON.stringify({ inquiries: 38, extracted: 11, yield: "28.9%" }),
    trackedKeywords: JSON.stringify(["pricing", "sales tool", "dm for details", "#growth"]),
    userId: "U-117bb402-3724-4580-9da9-01311b759889"
  },
  {
    id: "SA-whatsapp",
    platform: "WhatsApp",
    name: "WhatsApp Business API",
    handle: "+91 98765 43210 (Verified)",
    accountType: "Cloud API & Catalog Inbound",
    status: 1,
    followers: "Direct Channels",
    lastSync: "Just now",
    icon: "whatsapp",
    color: "#25D366",
    metrics: JSON.stringify({ inquiries: 54, extracted: 22, yield: "40.7%" }),
    trackedKeywords: JSON.stringify(["Catalog inquiries", "Click-to-WhatsApp Ads", "Support to Sale"]),
    userId: "U-117bb402-3724-4580-9da9-01311b759889"
  },
  {
    id: "SA-x",
    platform: "X",
    name: "X (Twitter) Mentions & DMs",
    handle: "@SaivyyHQ",
    accountType: "Verified Organization",
    status: 1,
    followers: "18.4K Followers",
    lastSync: "5 mins ago",
    icon: "x",
    color: "#0F1419",
    metrics: JSON.stringify({ inquiries: 25, extracted: 7, yield: "28.0%" }),
    trackedKeywords: JSON.stringify(["@SaivyyHQ", "crm alternative", "#salescrm", "b2b"]),
    userId: "U-117bb402-3724-4580-9da9-01311b759889"
  }
];

export const INITIAL_SOCIAL_INQUIRIES = [
  {
    id: "SI-101",
    platform: "LinkedIn",
    senderName: "Vikramaditya Sengupta",
    senderHandle: "@vikram-sengupta-ops",
    senderTitle: "VP of Sales & Revenue Operations",
    senderCompany: "Aegis FinServe Solutions",
    queryType: "Lead Gen Form",
    queryText: "Hi Saivyy Team, we are currently evaluating modern CRM suites to migrate our 45-member BFSI sales pipeline off legacy tools. Could you share your enterprise SLA, team pricing matrix, and arrange a personalized demo with our executive team next Tuesday?",
    intent: "High Intent",
    intentScore: 98,
    extractedData: JSON.stringify({
      email: "vikram.sengupta@aegisfin.com",
      phone: "+91 98201 44521",
      company: "Aegis FinServe Solutions",
      teamSize: "45 Seats",
      budget: "₹6,50,000 / yr",
      industry: "Fintech & BFSI",
      service: "Enterprise CRM Migration"
    }),
    status: "New",
    leadId: null,
    timestamp: "3 mins ago",
    replyText: null,
    userId: "U-117bb402-3724-4580-9da9-01311b759889"
  },
  {
    id: "SI-102",
    platform: "Instagram",
    senderName: "Ananya Deshmukh",
    senderHandle: "@ananya.designs.in",
    senderTitle: "Managing Director",
    senderCompany: "Studio Aura Interiors",
    queryType: "Direct Message",
    queryText: "Saw your reel on automated WhatsApp followups for design clients! We lose a lot of client inquiries between Instagram and quotation stage. How fast can we set this up for a team of 12 designers? Can you call me at +91 98402 11984 or email ananya@studioaura.in?",
    intent: "High Intent",
    intentScore: 94,
    extractedData: JSON.stringify({
      email: "ananya@studioaura.in",
      phone: "+91 98402 11984",
      company: "Studio Aura Interiors",
      teamSize: "12 Seats",
      budget: "₹2,40,000 / yr",
      industry: "Architecture & Interior Design",
      service: "WhatsApp Lead Followup Automation"
    }),
    status: "New",
    leadId: null,
    timestamp: "11 mins ago",
    replyText: null,
    userId: "U-117bb402-3724-4580-9da9-01311b759889"
  },
  {
    id: "SI-103",
    platform: "Meta",
    senderName: "Rajesh K. Agarwal",
    senderHandle: "@rajesh.agarwal.mfg",
    senderTitle: "Director of Procurement & Growth",
    senderCompany: "Kalyan Heavy Engineering Pvt Ltd",
    queryType: "Ad Ingestion (Manufacturing Campaign)",
    queryText: "Looking for lead tracking software for our Pune factory reps and regional distributors. We get 200+ raw dealer inquiries monthly. Need pipeline analytics and quote tracking. Contact: rajesh@kalyanheavyeng.com / 98220 54100",
    intent: "High Intent",
    intentScore: 96,
    extractedData: JSON.stringify({
      email: "rajesh@kalyanheavyeng.com",
      phone: "+91 98220 54100",
      company: "Kalyan Heavy Engineering Pvt Ltd",
      teamSize: "25 Seats",
      budget: "₹4,80,000 / yr",
      industry: "Industrial Manufacturing",
      service: "Dealer Pipeline & Quotation Tracking"
    }),
    status: "New",
    leadId: null,
    timestamp: "24 mins ago",
    replyText: null,
    userId: "U-117bb402-3724-4580-9da9-01311b759889"
  },
  {
    id: "SI-104",
    platform: "WhatsApp",
    senderName: "Dr. Sunita Rao",
    senderHandle: "+91 91673 89210",
    senderTitle: "Chief of Clinic Operations",
    senderCompany: "Apex Multispecialty Clinics",
    queryType: "WhatsApp Catalog Inbound",
    queryText: "Hello, clicked your ad on healthcare CRM workflow. We have 4 branch centers across Mumbai and need to track patient consultations and specialist follow-up appointments. Need to deploy before end of month. Please share quote to drsunita@apexclinics.org",
    intent: "High Intent",
    intentScore: 97,
    extractedData: JSON.stringify({
      email: "drsunita@apexclinics.org",
      phone: "+91 91673 89210",
      company: "Apex Multispecialty Clinics",
      teamSize: "35 Seats",
      budget: "₹5,40,000 / yr",
      industry: "Healthcare & Clinics",
      service: "Patient Consultation & Follow-up CRM"
    }),
    status: "New",
    leadId: null,
    timestamp: "42 mins ago",
    replyText: null,
    userId: "U-117bb402-3724-4580-9da9-01311b759889"
  },
  {
    id: "SI-105",
    platform: "X",
    senderName: "Rohan Bhatia",
    senderHandle: "@rohanb_tech",
    senderTitle: "Founder & CEO",
    senderCompany: "HyperScale LogiTech",
    queryType: "Public Mention",
    queryText: "Evaluating @SaivyyHQ vs HubSpot for a mid-market supply chain startup. Need cold calling integration, team metrics, and custom deal pipeline stages. How seamless is your telephony webhook? Anyone using it at scale?",
    intent: "Medium Intent",
    intentScore: 88,
    extractedData: JSON.stringify({
      email: "rohan@hyperscalelogi.in",
      phone: "+91 99100 87321",
      company: "HyperScale LogiTech",
      teamSize: "18 Seats",
      budget: "₹3,20,000 / yr",
      industry: "Logistics Tech",
      service: "Telephony & Deal Pipeline Integration"
    }),
    status: "New",
    leadId: null,
    timestamp: "1 hour ago",
    replyText: null,
    userId: "U-117bb402-3724-4580-9da9-01311b759889"
  },
  {
    id: "SI-106",
    platform: "LinkedIn",
    senderName: "Marcus Sterling",
    senderHandle: "@marcus-sterling-global",
    senderTitle: "Head of Channel Partnerships",
    senderCompany: "Sterling B2B Growth Agency",
    queryType: "Sponsored Post Comment",
    queryText: "We represent 15 manufacturing clients looking for an India-optimized CRM solution that supports regional currency and multi-tier distributor workflows. Would love to explore a reseller or partner integration with Saivyy.",
    intent: "Medium Intent",
    intentScore: 86,
    extractedData: JSON.stringify({
      email: "marcus@sterlingagency.co",
      phone: "+91 97110 33290",
      company: "Sterling B2B Growth Agency",
      teamSize: "Partner / Agency Tier",
      budget: "₹8,00,000+ Potential",
      industry: "Marketing Agency & Reseller",
      service: "Reseller & Partner Ecosystem Integration"
    }),
    status: "New",
    leadId: null,
    timestamp: "2 hours ago",
    replyText: null,
    userId: "U-117bb402-3724-4580-9da9-01311b759889"
  },
  {
    id: "SI-107",
    platform: "Instagram",
    senderName: "Devendra Pathak",
    senderHandle: "@dev_pathak_real",
    senderTitle: "Principal Broker",
    senderCompany: "Pathak Realty Ventures",
    queryType: "Story Reply",
    queryText: "Interested in demo for real estate agent commission tracking and buyer lead assignment. Email: devendra@pathakrealty.com",
    intent: "High Intent",
    intentScore: 92,
    extractedData: JSON.stringify({
      email: "devendra@pathakrealty.com",
      phone: "+91 98331 77652",
      company: "Pathak Realty Ventures",
      teamSize: "8 Seats",
      budget: "₹1,80,000 / yr",
      industry: "Real Estate",
      service: "Agent Commission & Lead Assignment"
    }),
    status: "Extracted",
    leadId: "L-demo-devendra",
    timestamp: "Yesterday",
    replyText: "Hi Devendra! We have connected your inquiry to our Real Estate specialist team. A CRM lead was created.",
    userId: "U-117bb402-3724-4580-9da9-01311b759889"
  }
];
